"use client";

import { useEffect, useState } from "react";
import { z } from "zod";
import { createClient } from "@/lib/supabase/client";

const schema = z.object({ nightly_price_kes: z.coerce.number().int().min(1).max(10_000_000), max_guests: z.coerce.number().int().min(1).max(100), check_in_time: z.string().min(1).max(30), check_out_time: z.string().min(1).max(30), whatsapp_number: z.string().regex(/^254[17]\d{8}$/, "Use format 2547XXXXXXXX"), tagline: z.string().min(1).max(160), welcome_paragraph: z.string().min(1).max(1000) });
type Settings = z.infer<typeof schema>;
const defaults: Settings = { nightly_price_kes: 0, max_guests: 6, check_in_time: "2:00 PM", check_out_time: "12 noon", whatsapp_number: "254727416611", tagline: "A considered stay in the Home of Champions.", welcome_paragraph: "Discover the Nevel three-bedroom apartment in Eldoret." };
export default function SettingsPage() {
  const [values,setValues]=useState<Settings>(defaults); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState("");
  useEffect(()=>{ void (async()=>{ const {data,error}=await createClient().from("site_settings").select("key,value"); if(error)setMessage(`Could not load settings: ${error.message}`); else if(data){const next={...defaults}; for(const row of data){ if(row.key in next){const key=row.key as keyof Settings; const value=row.value; if(typeof value==="string"||typeof value==="number") Object.assign(next,{[key]:value}); }} setValues(next);} setLoading(false); })(); },[]);
  function change(key:keyof Settings,value:string){setValues((current)=>({...current,[key]: key==="nightly_price_kes"||key==="max_guests"?Number(value):value}));}
  async function save(form:FormData){setSaving(true);setMessage(""); const parsed=schema.safeParse(Object.fromEntries(form)); if(!parsed.success){setMessage(parsed.error.issues[0]?.message??"Please check the settings.");setSaving(false);return;} const db=createClient(); const results=await Promise.all(Object.entries(parsed.data).map(([key,value])=>db.from("site_settings").upsert({key,value},{onConflict:"key"}))); const failed=results.find((result)=>result.error);setMessage(failed?.error?.message??"Settings saved.");setSaving(false);}
  const fields: {key:keyof Settings;label:string;type?:string;help?:string}[]=[{key:"nightly_price_kes",label:"Nightly price (KES)",type:"number"},{key:"max_guests",label:"Maximum guests",type:"number"},{key:"check_in_time",label:"Check-in time"},{key:"check_out_time",label:"Check-out time"},{key:"whatsapp_number",label:"WhatsApp number",help:"2547XXXXXXXX"},{key:"tagline",label:"Tagline"},{key:"welcome_paragraph",label:"Welcome paragraph"}];
  return <><h1 className="serif mb-5 text-4xl">Settings</h1>{loading?<p role="status">Loading settings…</p>:<form action={save} className="grid max-w-2xl gap-5">{fields.map(({key,label,type,help})=><label key={key} className="grid gap-2 text-sm">{label}{key==="welcome_paragraph"?<textarea name={key} rows={4} value={String(values[key])} onChange={(e)=>change(key,e.target.value)} className="min-h-24 rounded border border-[#dedbd2] bg-white px-3 py-3 text-base"/>:<input name={key} type={type??"text"} value={String(values[key])} onChange={(e)=>change(key,e.target.value)} className="min-h-12 rounded border border-[#dedbd2] bg-white px-3 text-base"/>}{help&&<span className="text-xs text-[#73736b]">{help}</span>}</label>)}{message&&<p role="status" className="text-sm">{message}</p>}<button disabled={saving} className="button button-dark w-fit">{saving?"Saving…":"Save settings"}</button></form>}</>;
}
