"use client";

import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Block = { id: number; start_date: string; end_date: string; reason: string | null };
type Booking = { id: number; name: string; check_in: string; check_out: string };
export default function AvailabilityPage() {
  const [blocks, setBlocks] = useState<Block[]>([]); const [bookings, setBookings] = useState<Booking[]>([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  async function load() { setLoading(true); const db = createClient(); const [a,b] = await Promise.all([db.from("blocked_dates").select("*").order("start_date"), db.from("enquiries").select("id,name,check_in,check_out").eq("status","confirmed").order("check_in")]); if (a.error || b.error) setError(`Unable to load availability: ${a.error?.message ?? b.error?.message}`); else { setBlocks(a.data ?? []); setBookings(b.data ?? []); } setLoading(false); }
  useEffect(() => { void load(); }, []);
  async function add(form: FormData) { setError(""); const start_date=String(form.get("start_date")??""); const end_date=String(form.get("end_date")??""); const reason=String(form.get("reason")??"").trim(); if (end_date <= start_date) { setError("End date must be after start date."); return; } const { error: saveError }=await createClient().from("blocked_dates").insert({start_date,end_date,reason:reason||null}); if(saveError) setError(saveError.message); else await load(); }
  async function remove(id:number) { const {error:deleteError}=await createClient().from("blocked_dates").delete().eq("id",id); if(deleteError) setError(deleteError.message); else setBlocks((rows)=>rows.filter((row)=>row.id!==id)); }
  return <><h1 className="serif mb-5 text-4xl">Availability</h1><form action={add} className="mb-8 grid gap-3 rounded-xl border border-[#dedbd2] p-4 sm:grid-cols-[1fr_1fr_1.5fr_auto] sm:items-end"><label className="grid gap-2 text-sm">Start date<input name="start_date" type="date" required className="min-h-12 rounded border border-[#dedbd2] bg-white px-3 text-base" /></label><label className="grid gap-2 text-sm">End date<input name="end_date" type="date" required className="min-h-12 rounded border border-[#dedbd2] bg-white px-3 text-base" /></label><label className="grid gap-2 text-sm">Reason<input name="reason" maxLength={120} className="min-h-12 rounded border border-[#dedbd2] bg-white px-3 text-base" /></label><button className="button button-dark">Block dates</button></form>{error&&<p role="alert" className="mb-4 rounded bg-red-50 p-3 text-sm text-red-900">{error}</p>}{loading?<p role="status">Loading availability…</p>:<div className="grid gap-8 md:grid-cols-2"><section><h2 className="serif mb-3 text-2xl">Blocked dates</h2>{blocks.length?blocks.map((b)=><div key={b.id} className="mb-2 flex items-center justify-between gap-2 rounded border border-[#dedbd2] p-3 text-sm"><span>{b.start_date} – {b.end_date}{b.reason&&<span className="block text-xs text-[#73736b]">{b.reason}</span>}</span><button onClick={()=>void remove(b.id)} className="min-h-11 px-3 text-red-800 underline">Delete</button></div>):<p className="text-sm">No blocked dates.</p>}</section><section><h2 className="serif mb-3 text-2xl">Confirmed stays</h2>{bookings.length?bookings.map((b)=><p key={b.id} className="mb-2 rounded border border-[#dedbd2] p-3 text-sm">{b.name}: {b.check_in} – {b.check_out}</p>):<p className="text-sm">No confirmed stays.</p>}</section></div>}</>;
}
