"use client";

import { useCallback, useEffect, useState } from "react";
import { format, parseISO } from "date-fns";
import { createClient } from "@/lib/supabase/client";

type Enquiry = { id: number; created_at: string; name: string; phone: string; email: string; check_in: string; check_out: string; guests: number; message: string | null; status: "new" | "contacted" | "confirmed" | "declined" };
type BlockedDate = { start_date: string; end_date: string };
const statuses = ["new", "contacted", "confirmed", "declined"] as const;
const dateLabel = (row: Enquiry) => `${format(parseISO(row.check_in), "d MMM")}–${format(parseISO(row.check_out), "d MMM yyyy")}`;

export default function Enquiries() {
  const [items, setItems] = useState<Enquiry[]>([]); const [blocks, setBlocks] = useState<BlockedDate[]>([]); const [filter, setFilter] = useState("all"); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); const db = createClient(); const [query, blocked] = await Promise.all([db.from("enquiries").select("*").order("created_at", { ascending: false }), db.from("blocked_dates").select("start_date,end_date")]); if (query.error || blocked.error) setError(`Unable to load enquiries: ${query.error?.message ?? blocked.error?.message}`); else { setItems(query.data ?? []); setBlocks(blocked.data ?? []); setError(""); } setLoading(false); }, []);
  useEffect(() => { void load(); }, [load]);
  const visible = filter === "all" ? items : items.filter((row) => row.status === filter);
  async function changeStatus(item: Enquiry, status: Enquiry["status"]) { setItems((current) => current.map((row) => row.id === item.id ? { ...row, status } : row)); const { error: updateError } = await createClient().from("enquiries").update({ status }).eq("id", item.id); if (updateError) { setError(`Status update failed: ${updateError.message}`); await load(); } }
  async function remove(item: Enquiry) { if (!window.confirm(`Delete the enquiry from ${item.name}? This cannot be undone.`)) return; const { error: deleteError } = await createClient().from("enquiries").delete().eq("id", item.id); if (deleteError) setError(`Delete failed: ${deleteError.message}`); else setItems((rows) => rows.filter((row) => row.id !== item.id)); }
  const clash = (item: Enquiry) => blocks.some((block) => item.check_in < block.end_date && block.start_date < item.check_out) || items.some((other) => other.id !== item.id && other.status === "confirmed" && item.check_in < other.check_out && other.check_in < item.check_out);
  const reply = (item: Enquiry) => `https://wa.me/${item.phone}?text=${encodeURIComponent(`Hi ${item.name}, thanks for your enquiry for ${dateLabel(item)} at Nevel Apartment. I’m following up about your stay.`)}`;
  return <section><div className="mb-4 flex flex-wrap gap-2" aria-label="Filter enquiries">{["all", ...statuses].map((status) => <button key={status} onClick={() => setFilter(status)} aria-pressed={filter === status} className={`min-h-11 rounded-full border px-4 text-sm capitalize ${filter === status ? "border-[#66715b] bg-[#66715b] text-white" : "border-[#dedbd2]"}`}>{status} ({status === "all" ? items.length : items.filter((row) => row.status === status).length})</button>)}</div>{error && <p role="alert" className="mb-4 rounded bg-red-50 p-3 text-sm text-red-900">{error}</p>}{loading ? <p role="status">Loading enquiries…</p> : visible.length === 0 ? <p className="rounded-lg border border-[#dedbd2] p-5 text-sm">No enquiries found.</p> : <div className="grid gap-4">{visible.map((item) => <article key={item.id} className={`rounded-xl border p-4 sm:p-5 ${item.status === "new" ? "border-[#66715b] bg-white/70" : "border-[#dedbd2] bg-white/40"}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">{item.name} {item.status === "new" && <span className="ml-2 rounded-full bg-[#66715b] px-2 py-1 text-xs text-white">New</span>}{clash(item) && <span className="ml-2 rounded-full bg-amber-100 px-2 py-1 text-xs text-amber-900">Dates clash</span>}</h2><p className="mt-1 text-sm">{dateLabel(item)} · {Math.max(0, Math.round((Date.parse(item.check_out) - Date.parse(item.check_in)) / 86400000))} nights · {item.guests} guests</p><p className="mt-1 text-xs text-[#73736b]">Received {format(new Date(item.created_at), "d MMM yyyy, h:mm a")}</p></div><label className="grid gap-1 text-xs text-[#73736b]">Status<select aria-label={`Status for ${item.name}`} className="min-h-11 rounded border border-[#dedbd2] bg-white px-2 text-base capitalize" value={item.status} onChange={(event) => void changeStatus(item, event.target.value as Enquiry["status"])}>{statuses.map((status) => <option key={status} value={status}>{status}</option>)}</select></label></div><div className="mt-4 grid gap-1 text-sm sm:grid-cols-2"><a href={`tel:${item.phone}`} className="min-h-11 py-2 underline">{item.phone}</a><a href={`mailto:${item.email}`} className="min-h-11 py-2 underline">{item.email}</a></div>{item.message && <p className="mt-2 whitespace-pre-wrap text-sm leading-6">{item.message}</p>}<div className="mt-4 flex flex-wrap gap-2"><a className="button button-dark min-h-11" href={reply(item)} target="_blank" rel="noopener noreferrer">Reply on WhatsApp</a><a className="button min-h-11" href={`mailto:${item.email}?subject=${encodeURIComponent("Your Nevel Apartment enquiry")}`}>Email</a><button className="min-h-11 px-3 text-sm text-red-800 underline" onClick={() => void remove(item)}>Delete</button></div></article>)}</div>}</section>;
}
